
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../base
patches:
- path: ingress-patch.yaml
  target:
    group: extensions
    version: v1beta1
    kind: Ingress
    name: productpage-ingress
