---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kbld.k14s.io/images: |
      - Metas:
        - Type: preresolved
          URL: carvel-harbor.customer0.io/bookinfo-bundle/dependencies@sha256:a437c65f69bcb3c08773c0ce774f08e12c0dba107eae9f816c640a603bd86ea4
        URL: carvel-harbor.customer0.io/bookinfo-bundle/dependencies@sha256:a437c65f69bcb3c08773c0ce774f08e12c0dba107eae9f816c640a603bd86ea4
  labels:
    app: details
    version: v1
  name: details-v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: details
      version: v1
  template:
    metadata:
      labels:
        app: details
        version: v1
    spec:
      containers:
      - image: carvel-harbor.customer0.io/bookinfo-bundle/dependencies@sha256:a437c65f69bcb3c08773c0ce774f08e12c0dba107eae9f816c640a603bd86ea4
        imagePullPolicy: IfNotPresent
        name: details
        ports:
        - containerPort: 9080
        securityContext:
          runAsUser: 1000
